Repository PathSnap/PathSnap-BE, pull requests merged in 2024-11, with the labels that each got.

#38 Feat/post-s3-1
  .DS_Store
  .idea/dataSources.xml
  Backend/.gitignore
  Backend/build.gradle
  Backend/src/main/java/com/pathsnap/Backend/Exception/S3NotFoundException.java
  Backend/src/main/java/com/pathsnap/Backend/Image/Config/S3Config.java
  Backend/src/main/java/com/pathsnap/Backend/Image/Controller/ImageController.java
  Backend/src/main/java/com/pathsnap/Backend/Image/Dto/ImageListResDTO.java
  Backend/src/main/java/com/pathsnap/Backend/Image/Dto/S3UploadReqDTO.java
  Backend/src/main/java/com/pathsnap/Backend/Image/Dto/S3UploadResDTO.java
  Backend/src/main/java/com/pathsnap/Backend/Image/Repository/ImageRepository.java
  Backend/src/main/java/com/pathsnap/Backend/Image/Service/ImageService.java
  Backend/src/main/resources/application.yml
  Backend/src/test/java/com/pathsnap/Backend/BackendApplicationTests.java
Labels: feat

#46 Feat/edit-photo
  Backend/src/main/java/com/pathsnap/Backend/Exception/PhotoRecordNotFoundException.java
  Backend/src/main/java/com/pathsnap/Backend/PhotoRecord/Controller/PhotoRecordController.java
  Backend/src/main/java/com/pathsnap/Backend/PhotoRecord/Dto/Req/PhotoRecordReqDto.java
  Backend/src/main/java/com/pathsnap/Backend/PhotoRecord/Repository/PhotoRecordRepository.java
  Backend/src/main/java/com/pathsnap/Backend/PhotoRecord/Service/PhotoRecordService/CreatePhotoService.java
  Backend/src/main/java/com/pathsnap/Backend/PhotoRecord/Service/PhotoRecordService/UpdatePhotoService.java
Labels: feat

#49 Feat/delete-Photo
  Backend/src/main/java/com/pathsnap/Backend/PhotoRecord/Controller/PhotoRecordController.java
  Backend/src/main/java/com/pathsnap/Backend/PhotoRecord/Service/PhotoRecordService/DeletePhotoService.java
Labels: feat

#50 Feat/get-SummaryPhoto
  Backend/src/main/java/com/pathsnap/Backend/PhotoRecord/Controller/PhotoRecordController.java
  Backend/src/main/java/com/pathsnap/Backend/PhotoRecord/Dto/Res/PhotoSummaryResDto.java
  Backend/src/main/java/com/pathsnap/Backend/PhotoRecord/Service/PhotoRecordService/SummaryPhotoService.java
Labels: feat

#51 Feat/patch-profile
  Backend/src/main/java/com/pathsnap/Backend/User/Controller/UserController.java
  Backend/src/main/java/com/pathsnap/Backend/User/Dto/Req/UserUpdateReqDTO.java
  Backend/src/main/java/com/pathsnap/Backend/User/Dto/Res/UserResDTO.java
  Backend/src/main/java/com/pathsnap/Backend/User/Service/UserService.java
Labels: feat

#59 Feat/get-SummaryPhoto
  Backend/src/main/java/com/pathsnap/Backend/PhotoRecord/Dto/Res/PhotoSummaryResDto.java
  Backend/src/main/java/com/pathsnap/Backend/PhotoRecord/Service/PhotoRecordService/SummaryPhotoService.java
  Backend/src/main/java/com/pathsnap/Backend/PhotoRecord/Service/PhotoRecordService/UpdatePhotoService.java
Labels: feat

#58 Feat/get-Home
  Backend/src/main/java/com/pathsnap/Backend/PhotoRecord/Controller/PhotoRecordController.java
  Backend/src/main/java/com/pathsnap/Backend/PhotoRecord/Dto/Res/PhotoDataResDto.java
  Backend/src/main/java/com/pathsnap/Backend/PhotoRecord/Dto/Res/PhotoLocationResDto.java
  Backend/src/main/java/com/pathsnap/Backend/PhotoRecord/Service/PhotoRecordService/GetPhotoLocationService.java
  Backend/src/main/java/com/pathsnap/Backend/Record/Repository/RecordRepository.java
Labels: feat

#60 Feat/save-route
  Backend/src/main/java/com/pathsnap/Backend/Coordinate/Dto/Req/CoordinateReqDto.java
  Backend/src/main/java/com/pathsnap/Backend/Coordinate/Entitiy/CoordinateEntity.java
  Backend/src/main/java/com/pathsnap/Backend/RouteRecord/Controller/RouteRecordController.java
  Backend/src/main/java/com/pathsnap/Backend/RouteRecord/Dto/Req/RouteReqDto.java
  Backend/src/main/java/com/pathsnap/Backend/RouteRecord/Entity/RouteRecordEntity.java
  Backend/src/main/java/com/pathsnap/Backend/RouteRecord/Service/RouteRecordSaveService.java
Labels: feat

#62 Fix/get-Record
  Backend/src/main/java/com/pathsnap/Backend/Coordinate/Dto/Res/CoordinateResDto.java
  Backend/src/main/java/com/pathsnap/Backend/PhotoRecord/Dto/Req/PhotoUpdateReqDto.java
  Backend/src/main/java/com/pathsnap/Backend/PhotoRecord/Dto/Res/PhotoRecordResDto.java
  Backend/src/main/java/com/pathsnap/Backend/PhotoRecord/Dto/Res/PhotoUpdateResDto.java
  Backend/src/main/java/com/pathsnap/Backend/Record/Controller/RecordController.java
  Backend/src/main/java/com/pathsnap/Backend/Record/Dto/Req/RecordUpdateReqDto.java
  Backend/src/main/java/com/pathsnap/Backend/Record/Dto/Res/RecordUpdateResDto.java
  Backend/src/main/java/com/pathsnap/Backend/Record/Service/RecordDetailService.java
  Backend/src/main/java/com/pathsnap/Backend/Record/Service/RecordUpdateService.java
  Backend/src/main/java/com/pathsnap/Backend/RouteRecord/Dto/Req/RouteUpdateReqDto.java
  Backend/src/main/java/com/pathsnap/Backend/RouteRecord/Dto/Res/RouteRecordResDto.java
  Backend/src/main/java/com/pathsnap/Backend/RouteRecord/Dto/Res/RouteUpdateResDto.java
  Backend/src/main/java/com/pathsnap/Backend/RouteRecord/Repository/RouteRecordRepository.java
  Backend/src/main/java/com/pathsnap/Backend/RouteRecord/Service/RouteRecordSaveService.java
Labels: feat

#66 Refactor/edit
  Backend/src/main/java/com/pathsnap/Backend/Exception/S3NotFoundException.java
  Backend/src/main/java/com/pathsnap/Backend/Image/Dto/Res/ImageListResDto.java
  Backend/src/main/java/com/pathsnap/Backend/Image/Dto/Res/ImageResDto.java
  Backend/src/main/java/com/pathsnap/Backend/PackTrip/Controller/PackTripController.java
  Backend/src/main/java/com/pathsnap/Backend/PackTrip/Dto/Req/PackTripReqDto.java
  Backend/src/main/java/com/pathsnap/Backend/PackTrip/Dto/Res/PackTripResDto.java
  Backend/src/main/java/com/pathsnap/Backend/PackTrip/Service/PackTripService.java
  Backend/src/main/java/com/pathsnap/Backend/PhotoRecord/Controller/PhotoRecordController.java
  Backend/src/main/java/com/pathsnap/Backend/PhotoRecord/Dto/Res/PhotoRecordResDto.java
  Backend/src/main/java/com/pathsnap/Backend/PhotoRecord/Service/PhotoRecordService/CreatePhotoService.java
  Backend/src/main/java/com/pathsnap/Backend/PhotoRecord/Service/PhotoRecordService/DeletePhotoService.java
  Backend/src/main/java/com/pathsnap/Backend/PhotoRecord/Service/PhotoRecordService/GetPhotoLocationService.java
  Backend/src/main/java/com/pathsnap/Backend/PhotoRecord/Service/PhotoRecordService/SummaryPhotoService.java
  Backend/src/main/java/com/pathsnap/Backend/PhotoRecord/Service/PhotoRecordService/UpdatePhotoService.java
  Backend/src/main/java/com/pathsnap/Backend/Record/Controller/RecordController.java
  Backend/src/main/java/com/pathsnap/Backend/Record/Service/RecordDeleteService.java
  Backend/src/main/java/com/pathsnap/Backend/Record/Service/RecordDetailService.java
  Backend/src/main/java/com/pathsnap/Backend/Record/Service/RecordEditService.java
  Backend/src/main/java/com/pathsnap/Backend/Record/Service/RecordStartService.java
  Backend/src/main/java/com/pathsnap/Backend/Record/Service/RecordUpdateService.java
  Backend/src/main/java/com/pathsnap/Backend/RouteRecord/Controller/RouteRecordController.java
  Backend/src/main/java/com/pathsnap/Backend/RouteRecord/Dto/Res/RouteRecordStartDto.java
  Backend/src/main/java/com/pathsnap/Backend/RouteRecord/Service/RouteRecordSaveService.java
  Backend/src/main/java/com/pathsnap/Backend/RouteRecord/Service/RouteRecordStartService.java
  Backend/src/main/java/com/pathsnap/Backend/S3/Controller/S3Controller.java
  Backend/src/main/java/com/pathsnap/Backend/S3/Dto/Req/S3UpdateReqDto.java
  Backend/src/main/java/com/pathsnap/Backend/S3/Dto/Req/S3UploadReqDto.java
  Backend/src/main/java/com/pathsnap/Backend/S3/Dto/Res/S3ListResDto.java
  Backend/src/main/java/com/pathsnap/Backend/S3/Dto/Res/S3ResDto.java
  Backend/src/main/java/com/pathsnap/Backend/S3/Service/S3Service.java
  Backend/src/main/java/com/pathsnap/Backend/User/Controller/UserController.java
  Backend/src/main/java/com/pathsnap/Backend/User/Dto/Req/UserUpdateReqDto.java
  Backend/src/main/java/com/pathsnap/Backend/User/Dto/Res/CalendarResDto.java
  Backend/src/main/java/com/pathsnap/Backend/User/Dto/Res/LocationResDto.java
  Backend/src/main/java/com/pathsnap/Backend/User/Dto/Res/UserResDto.java
  Backend/src/main/java/com/pathsnap/Backend/User/Service/CalendarListService.java
  Backend/src/main/java/com/pathsnap/Backend/User/Service/CalendarPackTripService.java
  Backend/src/main/java/com/pathsnap/Backend/User/Service/LocationService.java
  Backend/src/main/java/com/pathsnap/Backend/User/Service/UserService.java
Labels: refactor

#71 Refactor/edit
  Backend/src/main/java/com/pathsnap/Backend/Coordinate/Component/AddCoordinate.java
  Backend/src/main/java/com/pathsnap/Backend/Coordinate/Component/CreateCoordinate.java
  Backend/src/main/java/com/pathsnap/Backend/Exception/RouteRecordNotFoundException.java
  Backend/src/main/java/com/pathsnap/Backend/ImagePhoto/Component/CreateImagePhoto.java
  Backend/src/main/java/com/pathsnap/Backend/ImagePhoto/Component/EditImagePhoto.java
  Backend/src/main/java/com/pathsnap/Backend/PhotoRecord/Component/CheckPhotoRecord.java
  Backend/src/main/java/com/pathsnap/Backend/PhotoRecord/Component/CreatePhotoRecord.java
  Backend/src/main/java/com/pathsnap/Backend/PhotoRecord/Component/EditPhotoRecord.java
  Backend/src/main/java/com/pathsnap/Backend/PhotoRecord/Component/GetPhotoRecord.java
  Backend/src/main/java/com/pathsnap/Backend/PhotoRecord/Component/PhotoLocation/FilterPhotoLocation.java
  Backend/src/main/java/com/pathsnap/Backend/PhotoRecord/Component/PhotoLocation/RadiusCalculator.java
  Backend/src/main/java/com/pathsnap/Backend/PhotoRecord/Component/UpdateSeqPhotoRecord.java
  Backend/src/main/java/com/pathsnap/Backend/PhotoRecord/Controller/PhotoRecordController.java
  Backend/src/main/java/com/pathsnap/Backend/PhotoRecord/Service/CreatePhotoService.java
  Backend/src/main/java/com/pathsnap/Backend/PhotoRecord/Service/DeletePhotoService.java
  Backend/src/main/java/com/pathsnap/Backend/PhotoRecord/Service/EditPhotoService.java
  Backend/src/main/java/com/pathsnap/Backend/PhotoRecord/Service/GetPhotoLocationService.java
  Backend/src/main/java/com/pathsnap/Backend/PhotoRecord/Service/PhotoRecordService/CreatePhotoService.java
  Backend/src/main/java/com/pathsnap/Backend/PhotoRecord/Service/PhotoRecordService/GetPhotoLocationService.java
  Backend/src/main/java/com/pathsnap/Backend/PhotoRecord/Service/PhotoRecordService/UpdatePhotoService.java
  Backend/src/main/java/com/pathsnap/Backend/PhotoRecord/Service/SummaryPhotoService.java
  Backend/src/main/java/com/pathsnap/Backend/Record/Component/CheckRecord.java
  Backend/src/main/java/com/pathsnap/Backend/Record/Component/CreateRecord.java
  Backend/src/main/java/com/pathsnap/Backend/Record/Component/EditRecordName.java
  Backend/src/main/java/com/pathsnap/Backend/Record/Component/GetRecord.java
  Backend/src/main/java/com/pathsnap/Backend/Record/Controller/RecordController.java
  Backend/src/main/java/com/pathsnap/Backend/Record/Service/CreateRecordService.java
  Backend/src/main/java/com/pathsnap/Backend/Record/Service/DeleteRecordService.java
  Backend/src/main/java/com/pathsnap/Backend/Record/Service/EditRecordService.java
  Backend/src/main/java/com/pathsnap/Backend/Record/Service/GetRecordService.java
  Backend/src/main/java/com/pathsnap/Backend/Record/Service/RecordDeleteService.java
  Backend/src/main/java/com/pathsnap/Backend/Record/Service/RecordDetailService.java
  Backend/src/main/java/com/pathsnap/Backend/Record/Service/RecordStartService.java
  Backend/src/main/java/com/pathsnap/Backend/Record/Service/RecordUpdateService.java
  Backend/src/main/java/com/pathsnap/Backend/Record/Service/UpdateSeqRecordService.java
  Backend/src/main/java/com/pathsnap/Backend/RouteRecord/Component/CheckRouteRecord.java
  Backend/src/main/java/com/pathsnap/Backend/RouteRecord/Component/CreateRouteRecord.java
  Backend/src/main/java/com/pathsnap/Backend/RouteRecord/Component/DetermineTransportMode.java
  Backend/src/main/java/com/pathsnap/Backend/RouteRecord/Component/GetRouteRecord.java
  Backend/src/main/java/com/pathsnap/Backend/RouteRecord/Component/UpdateSeqRouteReecord.java
  Backend/src/main/java/com/pathsnap/Backend/RouteRecord/Controller/RouteRecordController.java
  Backend/src/main/java/com/pathsnap/Backend/RouteRecord/Service/CreateRouteRecordService.java
  Backend/src/main/java/com/pathsnap/Backend/RouteRecord/Service/EditRouteRecordService.java
  Backend/src/main/java/com/pathsnap/Backend/RouteRecord/Service/RouteRecordSaveService.java
  Backend/src/main/java/com/pathsnap/Backend/RouteRecord/Service/RouteRecordStartService.java
  Backend/src/main/java/com/pathsnap/Backend/User/Compnent/GetUser.java
  Backend/src/main/java/com/pathsnap/Backend/User/Compnent/UserCheck.java
Labels: refactor

#72 Chore/swagger record
  Backend/src/main/java/com/pathsnap/Backend/Record/Controller/RecordController.java
  Backend/src/main/java/com/pathsnap/Backend/Record/Controller/RecordControllerDocs.java
Labels: chore

#99 Feat/webSocket-getRouteStart
  Backend/build.gradle
  Backend/src/main/java/com/pathsnap/Backend/Record/Repository/RecordRepository.java
  Backend/src/main/java/com/pathsnap/Backend/WebSocket/Config/WebSocketConfig.java
  Backend/src/main/java/com/pathsnap/Backend/WebSocket/Controller/WebSocketController.java
  Backend/src/main/java/com/pathsnap/Backend/WebSocket/WebSocketService/WebSocketAuthService.java
Labels: feat

#108 Chore/swagger-PhotoRecord
  Backend/src/main/java/com/pathsnap/Backend/PhotoRecord/Controller/PhotoRecordController.java
  Backend/src/main/java/com/pathsnap/Backend/PhotoRecord/Controller/PhotoRecordControllerDocs.java
  Backend/src/main/java/com/pathsnap/Backend/Record/Controller/RecordControllerDocs.java
Labels: chore

#112 Feat/api-Friend
  Backend/src/main/java/com/pathsnap/Backend/Exception/FriendNotFoundException.java
  Backend/src/main/java/com/pathsnap/Backend/Friend/Component/AddFriend.java
  Backend/src/main/java/com/pathsnap/Backend/Friend/Component/CheckFriend.java
  Backend/src/main/java/com/pathsnap/Backend/Friend/Controller/FriendController.java
  Backend/src/main/java/com/pathsnap/Backend/Friend/Dto/Res/FriendAddResDto.java
  Backend/src/main/java/com/pathsnap/Backend/Friend/Dto/Res/FriendListResDto.java
  Backend/src/main/java/com/pathsnap/Backend/Friend/Dto/Res/FriendSearchResDto.java
  Backend/src/main/java/com/pathsnap/Backend/Friend/Entity/Friend1Entity.java
  Backend/src/main/java/com/pathsnap/Backend/Friend/Repository/FriendRepository.java
  Backend/src/main/java/com/pathsnap/Backend/Friend/Service/AddFriendService.java
  Backend/src/main/java/com/pathsnap/Backend/Friend/Service/DeleteFriendService.java
  Backend/src/main/java/com/pathsnap/Backend/Friend/Service/ListFriendService.java
  Backend/src/main/java/com/pathsnap/Backend/Friend/Service/SearchFriendService.java
  Backend/src/main/java/com/pathsnap/Backend/Record/Component/GetRecord.java
  Backend/src/main/java/com/pathsnap/Backend/Record/Entity/Record1Entity.java
  Backend/src/main/java/com/pathsnap/Backend/Record/Repository/RecordRepository.java
  Backend/src/main/java/com/pathsnap/Backend/User/Dto/Res/UserStoryResDto.java
  Backend/src/main/java/com/pathsnap/Backend/User/Entity/User1Entity.java
  Backend/src/main/java/com/pathsnap/Backend/User/Repository/UserRepository.java
Labels: feat

#113 Chore/swagger-s3
  Backend/src/main/java/com/pathsnap/Backend/S3/Controller/S3Controller.java
  Backend/src/main/java/com/pathsnap/Backend/S3/Controller/S3ControllerDocs.java
Labels: chore

#116 Chore/swagger-Friend
  Backend/src/main/java/com/pathsnap/Backend/Friend/Controller/FriendController.java
  Backend/src/main/java/com/pathsnap/Backend/Friend/Controller/FriendControllerDocs.java
  Backend/src/main/java/com/pathsnap/Backend/PhotoRecord/Controller/PhotoRecordControllerDocs.java
  Backend/src/main/java/com/pathsnap/Backend/RouteRecord/Controller/RouteRecordControllerDocs.java
Labels: chore

#92 Feat/security-Spring
  Backend/build.gradle
  Backend/src/main/java/com/pathsnap/Backend/Config/CorsMvcConfig.java
  Backend/src/main/java/com/pathsnap/Backend/Config/SecurityConfig.java
  Backend/src/main/java/com/pathsnap/Backend/Friend/Controller/FriendController.java
  Backend/src/main/java/com/pathsnap/Backend/Oauth2Login/Controller/Oauth2Controller.java
  Backend/src/main/java/com/pathsnap/Backend/Oauth2Login/Dto/Res/CustomOauth2UserResDto.java
  Backend/src/main/java/com/pathsnap/Backend/Oauth2Login/Dto/Res/NaverRes.java
  Backend/src/main/java/com/pathsnap/Backend/Oauth2Login/Dto/Res/OAuth2Res.java
  Backend/src/main/java/com/pathsnap/Backend/Oauth2Login/Dto/Res/Oauth2UserResDto.java
  Backend/src/main/java/com/pathsnap/Backend/Oauth2Login/Entity/RefreshEntity.java
  Backend/src/main/java/com/pathsnap/Backend/Oauth2Login/Jwt/Component/CustomLogoutFilter.java
  Backend/src/main/java/com/pathsnap/Backend/Oauth2Login/Jwt/Component/JwtFilter.java
  Backend/src/main/java/com/pathsnap/Backend/Oauth2Login/Jwt/Component/JwtUtil.java
  Backend/src/main/java/com/pathsnap/Backend/Oauth2Login/Repository/RefreshRepository.java
  Backend/src/main/java/com/pathsnap/Backend/Oauth2Login/Service/CustomOAuth2UserService.java
  Backend/src/main/java/com/pathsnap/Backend/Oauth2Login/Service/CustomSuccessHandler.java
  Backend/src/main/java/com/pathsnap/Backend/Oauth2Login/Service/RefreshService.java
  Backend/src/main/java/com/pathsnap/Backend/PackTrip/Controller/PackTripController.java
  Backend/src/main/java/com/pathsnap/Backend/PhotoRecord/Controller/PhotoRecordController.java
  Backend/src/main/java/com/pathsnap/Backend/Record/Controller/RecordController.java
  Backend/src/main/java/com/pathsnap/Backend/RouteRecord/Controller/RouteRecordController.java
  Backend/src/main/java/com/pathsnap/Backend/S3/Controller/S3Controller.java
  Backend/src/main/java/com/pathsnap/Backend/SwaggerConfig.java
  Backend/src/main/java/com/pathsnap/Backend/User/Controller/UserController.java
  Backend/src/main/java/com/pathsnap/Backend/User/Entity/User1Entity.java
  Backend/src/main/java/com/pathsnap/Backend/User/Repository/UserRepository.java
  Backend/src/main/java/com/pathsnap/Backend/WebSocket/Controller/WebSocketController.java
  Backend/src/main/resources/application.yml
  Backend/src/test/java/com/pathsnap/Backend/BackendApplicationTests.java
Labels: feat

#147 Fix/fix-reissue-Oauth2Login
  Backend/src/main/java/com/pathsnap/Backend/Oauth2Login/Controller/Oauth2Controller.java
  Backend/src/main/java/com/pathsnap/Backend/Oauth2Login/Dto/Res/ReissueResDto.java
Labels: feat

#123 Fix/get-image
  Backend/src/main/java/com/pathsnap/Backend/PhotoRecord/Repository/PhotoRecordRepository.java
  Backend/src/main/java/com/pathsnap/Backend/User/Compnent/GetCalendar.java
  Backend/src/main/java/com/pathsnap/Backend/User/Compnent/GetUserLocation.java
  Backend/src/main/java/com/pathsnap/Backend/User/Compnent/Small/GetUserMainImage.java
Labels: bug

#152 Fix/profile-patch
  Backend/src/main/java/com/pathsnap/Backend/User/Compnent/UpdateUserProfile.java
  Backend/src/main/java/com/pathsnap/Backend/User/Dto/Req/UserUpdateReqDto.java
Labels: bug
